'use strict';
const D=window.HOMA_DATA, BN=1e9, $=s=>document.querySelector(s), sum=(a,k)=>a.reduce((s,x)=>s+(typeof k==='function'?k(x):x[k]||0),0);
const fa=(n,d=0)=>Number(n||0).toLocaleString('fa-IR',{maximumFractionDigits:d,minimumFractionDigits:d});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={page:location.hash.slice(1)||'overview',year:'1404',group:'all',unit:'bn',fx:90000,collect:20,save:3,inflation:5};
const metricDetails=window.HOMA_METRICS;
const pages={overview:['نمای کلان هلدینگ','EXECUTIVE OVERVIEW','پایش رشد و تبدیل آن به ارزش.'],projects:['سلامت سبد پروژه‌ها','PORTFOLIO PERFORMANCE','رشد، زمان و هزینه؛ در یک قاب تصمیم.'],cash:['نقدینگی و سرمایه در گردش','CASH & WORKING CAPITAL','درآمد زمانی نقدینگی می‌شود که وصول شود.'],procurement:['خرید و زنجیرهٔ تأمین','PROCUREMENT INTELLIGENCE','کنترل هزینه از اولین سفارش آغاز می‌شود.'],customers:['کارفرمایان و توسعه بازار','CUSTOMER & GROWTH','ارزش قرارداد، کیفیت وصول و فرصت‌های آینده.'],people:['منابع انسانی و کیفیت اجرا','PEOPLE & DELIVERY','هزینهٔ نیروی انسانی در کنار تجربهٔ کارفرما.'],decisions:['آزمایشگاه تصمیم','DECISION LAB','با تغییر فرض‌ها، اثر هر تصمیم پیش از اجرا برآورد می‌شود.'],quality:['اعتماد به داده','DATA TRUST & LINEAGE','هر شاخص، یک تعریف روشن و یک مسیر قابل ردیابی.']};
const icons=['<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>','<path d="M3 21V8l8-5v18M11 10l10-3v14M6 10v1m0 4v1m9-3v1m3-2v1M2 21h20"/>','<path d="M3 7h18v13H3zM3 7l13-4v4M16 12h5v5h-5z"/>','<path d="M3 5h3l3 12h11l2-9H7M10 21h.1M19 21h.1"/>','<circle cx="9" cy="7" r="3"/><path d="M2 20v-3a7 7 0 0114 0v3M16 4a3 3 0 010 6M18 14a5 5 0 014 5"/>','<path d="M3 20h18M6 17V9m6 8V3m6 14v-5"/>','<path d="M9 3h6M10 3v6L4 19a1 1 0 001 2h14a1 1 0 001-2L14 9V3M8 14h8"/>','<path d="M12 2l9 4v7c0 5-9 9-9 9s-9-4-9-9V6zM7 12l3 3 7-7"/>'];
$('#nav').innerHTML=Object.keys(pages).map((k,i)=>`<a href="#${k}" data-page="${k}"><svg viewBox="0 0 24 24">${icons[i]}</svg>${pages[k][0]}</a>`).join('');
[...new Set(D.companies.map(x=>x.group_name))].forEach(x=>$('#group').insertAdjacentHTML('beforeend',`<option>${x}</option>`));
const projectMap=Object.fromEntries(D.projects.map(x=>[x.project_id,x])), customerMap=Object.fromEntries(D.customers.map(x=>[x.customer_id,x])),supplierMap=Object.fromEntries(D.suppliers.map(x=>[x.supplier_id,x]));
const divisor=()=>state.unit==='bn'?BN:state.unit==='hem'?1e12:state.fx*1e6;
const unit=()=>state.unit==='bn'?'میلیارد تومان':state.unit==='hem'?'همت':'میلیون دلار فرضی';
const money=(n,d)=>fa(n/divisor(),d??(state.unit==='bn'?0:2));
const percent=(n,d=1)=>fa(n*100,d)+'٪';
function context(){
 const projects=D.projects.filter(p=>state.group==='all'||p.group_name===state.group),ids=new Set(projects.map(p=>p.project_id));
 const periods=D.periods.filter(p=>state.year==='all'||p.jalali_year===+state.year),periodIds=new Set(periods.map(p=>p.period_id));
 const all=D.monthly.filter(x=>ids.has(x.project_id)),m=all.filter(x=>periodIds.has(x.period_id));
 const ar=D.receivables.filter(x=>ids.has(x.project_id)),ap=D.payables.filter(x=>ids.has(x.project_id));
 const campaigns=D.campaigns.filter(x=>(state.group==='all'||D.companies[x.company_id-1].group_name===state.group)&&periodIds.has(x.period_id));
 const allCampaigns=D.campaigns.filter(x=>state.group==='all'||D.companies[x.company_id-1].group_name===state.group);
 const opening=+D.meta.opening_cash_toman*sum(projects,'contract_toman')/sum(D.projects,'contract_toman');
 const cash=opening+sum(all,'receipts_toman')-sum(all,'payments_toman')-sum(allCampaigns,'spend_toman');
 const revenue=sum(m,'revenue_toman'),cost=sum(m,'cost_toman'),margin=revenue?(revenue-cost)/revenue:0;
 const lastYear=state.year==='all'?null:+state.year-1;
 const prev=all.filter(x=>lastYear&&D.periods[x.period_id-1].jalali_year===lastYear),prevRevenue=sum(prev,'revenue_toman'),prevCost=sum(prev,'cost_toman');
 return {projects,ids,periods,periodIds,all,m,ar,ap,campaigns,allCampaigns,opening,cash,revenue,cost,margin,prev,prevRevenue,prevMargin:prevRevenue?(prevRevenue-prevCost)/prevRevenue:null};
}
function pill(text,type='neutral'){return `<span class="pill ${type}">${text}</span>`}
function kpi(title,value,suffix,note='',type='neutral',icon='↗',drill=true){const id=drill&&metricDetails.routeForTitle[title],tag=id?'a':'article',attrs=id?` href="#metric/${id}" data-metric="${id}" aria-label="جزئیات ${title}"`:'';return `<${tag} class="kpi glass${id?' kpi-link':''}"${attrs}><div class="kpi-top">${title}<span class="kpi-icon">${icon}</span></div><div class="kpi-value">${value}<small>${suffix}</small></div><div class="kpi-foot">${note?pill(note,type):''}</div>${id?'<span class="kpi-open">نمایش نمودار و جزئیات ←</span>':''}</${tag}>`}
function panel(title,sub,body,tag=''){return `<section class="panel glass"><div class="panel-head"><div><h3>${title}</h3><div class="sub">${sub}</div></div>${tag?`<span class="panel-tag">${tag}</span>`:''}</div>${body}</section>`}
function insight(n,title,body,page){return `<div class="insight"><span class="num">${fa(n,0)}</span><div><h4>${title}</h4><p>${body}</p>${page?`<button data-go="${page}">بررسی جزئیات ←</button>`:''}</div></div>`}
function sumTrend(c,key){return c.periods.map(p=>sum(c.m.filter(x=>x.period_id===p.period_id),key))}
function lineChart(labels,series,{height=240,minZero=true,format=money}={}){
 const w=650,h=height,l=58,r=17,t=25,b=34,cw=w-l-r,ch=h-t-b;
 let vals=series.flatMap(s=>s.values),lo=minZero?Math.min(0,...vals):Math.min(...vals),hi=Math.max(...vals);if(hi===lo)hi=lo+1;
 const pad=(hi-lo)*.12;hi+=pad;if(lo<0)lo-=pad;
 const x=i=>l+i*cw/Math.max(labels.length-1,1),y=v=>t+(hi-v)/(hi-lo)*ch;
 let svg=`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="نمودار روند ${series.map(s=>s.name).join(' و ')}">`;
 for(let i=0;i<5;i++){const v=lo+(hi-lo)*i/4;svg+=`<line class="axis-line" x1="${l}" y1="${y(v)}" x2="${w-r}" y2="${y(v)}"/><text x="${l-10}" y="${y(v)+4}" text-anchor="end">${format(v)}</text>`}
 const ticks=new Set(Array.from({length:Math.min(6,labels.length)},(_,i)=>Math.round(i*(labels.length-1)/Math.min(5,labels.length-1))));
 labels.forEach((s,i)=>{if(ticks.has(i))svg+=`<text x="${x(i)}" y="${h-10}" text-anchor="middle">${esc(s)}</text>`});
 series.forEach((s,si)=>{const path=s.values.map((v,i)=>(i?'L':'M')+x(i).toFixed(1)+','+y(v).toFixed(1)).join(' ');
 if(si===0&&minZero){svg+=`<path d="${path} L${x(s.values.length-1)},${y(0)} L${x(0)},${y(0)}Z" fill="${s.color}" opacity=".06"/>`}
 svg+=`<path d="${path}" fill="none" stroke="${s.color}" stroke-width="2.7" stroke-linecap="round" stroke-linejoin="round" ${s.dashed?'stroke-dasharray="5 5"':''}/>`;
 s.values.forEach((v,i)=>svg+=`<circle cx="${x(i)}" cy="${y(v)}" r="3" fill="${s.color}"/><circle cx="${x(i)}" cy="${y(v)}" r="10" fill="transparent" data-tip="${esc(labels[i]+' · '+s.name+' : '+format(v))}"/>`);
 });
 return svg+'</svg>'+`<div class="legend">${series.map(s=>`<span><i style="background:${s.color}"></i>${s.name}</span>`).join('')}</div>`;
}
function bars(items,opts={}){
 const max=Math.max(...items.map(x=>x.value),1),total=sum(items,'value');
 return items.map(x=>`<div class="metric-line"><div class="name">${esc(x.name)}<div class="track"><span style="width:${Math.max(0,x.value/max*100)}%;${x.color?'background:'+x.color:''}"></span></div></div><div class="amount">${opts.count?fa(x.value):money(x.value)}<small>${x.note||percent(x.value/total)}</small></div></div>`).join('');
}
const risk=p=>p.spi<.85||p.cpi<.90;
const riskRank=p=>(1-p.cpi)*.5+(1-p.spi)*.5;
function projectsTable(ps,limit=60){return `<div class="table-wrap"><table><thead><tr><th>پروژه / شرکت</th><th>پیشرفت واقعی</th><th>CPI</th><th>SPI</th><th>وضعیت</th><th>قرارداد (${unit()})</th></tr></thead><tbody>${[...ps].sort((a,b)=>riskRank(b)-riskRank(a)).slice(0,limit).map(p=>`<tr data-project="${p.project_id}"><td class="project-name">${p.name}<span class="secondary">${p.company_name}</span></td><td>${percent(p.progress,0)}<div class="progress"><b style="width:${p.progress*100}%"></b></div></td><td dir="ltr">${fa(p.cpi,2)}</td><td dir="ltr">${fa(p.spi,2)}</td><td>${pill(risk(p)?'نیازمند مداخله':p.spi<.95?'تحت پایش':'پایدار',risk(p)?'negative':p.spi<.95?'warning':'positive')}</td><td>${money(p.contract_toman)}</td></tr>`).join('')}</tbody></table></div>`}
function scatter(ps){
 const w=580,h=282,l=52,t=26,b=36,r=28,xmin=.75,xmax=1.12,ymin=.55,ymax=1.13,x=v=>l+(v-xmin)/(xmax-xmin)*(w-l-r),y=v=>t+(ymax-v)/(ymax-ymin)*(h-t-b);
 let s=`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="ماتریس عملکرد زمان و هزینه"><rect x="${l}" y="${t}" width="${w-l-r}" height="${h-t-b}" rx="10" fill="#f5edf4"/><rect x="${x(1)}" y="${t}" width="${x(xmax)-x(1)}" height="${y(1)-t}" fill="#f4eadb"/>`;
 [.8,.9,1,1.1].forEach(v=>s+=`<line x1="${x(v)}" y1="${t}" x2="${x(v)}" y2="${h-b}" class="axis-line"/><text x="${x(v)}" y="${h-b+18}" text-anchor="middle">${fa(v,1)}</text>`);
 [.6,.8,1].forEach(v=>s+=`<line x1="${l}" y1="${y(v)}" x2="${w-r}" y2="${y(v)}" class="axis-line"/><text x="${l-10}" y="${y(v)+4}" text-anchor="end">${fa(v,1)}</text>`);
 s+=`<text x="${w/2}" y="${h-2}" text-anchor="middle">کارایی هزینه CPI →</text><text x="${l+60}" y="15" text-anchor="middle">کارایی زمان SPI</text>`;
 ps.forEach(p=>{const rad=4+Math.sqrt(p.budget_toman/BN)/13,color=risk(p)?'#b45e69':'#8b55a1';s+=`<circle cx="${x(p.cpi)}" cy="${y(p.spi)}" r="${rad}" fill="${color}" opacity=".72" stroke="#fff" stroke-width="1.2" data-project="${p.project_id}" data-tip="${esc(p.name+' · CPI '+fa(p.cpi,2)+' · SPI '+fa(p.spi,2))}"/>`});return s+'</svg><div class="footnote">هر دایره یک پروژه؛ اندازه متناسب با بودجه. مقدار کمتر از ۱ یعنی عملکرد ضعیف‌تر از خط مبنا. جزئیات هر پروژه با انتخاب دایره نمایش داده می‌شود.</div>';
}
function forecast(c){
 const last=c.all.filter(x=>x.period_id>=34),overdue=sum(c.ar.filter(x=>x.overdue_days>0),'balance_toman'),ap=sum(c.ap,'balance_toman');
 const arExpected=sum(c.ar,x=>x.balance_toman*(x.overdue_days>180?.25:x.overdue_days>90?.45:x.overdue_days>0?.7:.88));
 const qcost=sum(last,'cost_toman'),qrev=sum(last,'revenue_toman'),material=sum(D.costs.filter(x=>c.ids.has(x.project_id)&&x.period_id>=34&&x.category==='materials'),'amount_toman');
 const base=[c.cash],scenario=[c.cash],floor=c.cash*.30;
 const uncollectedOverdue=sum(c.ar.filter(x=>x.overdue_days>0),x=>x.balance_toman*(1-(x.overdue_days>180?.25:x.overdue_days>90?.45:.7)));
 const grossRecovery=Math.min(overdue*state.collect/100,uncollectedOverdue);
 const recover=grossRecovery*.99; // Capped to balances not already expected in the baseline; 1% incentive.
 const savings=material*state.save/100,inflation=material*state.inflation/100;
 for(let i=0;i<13;i++){
  const inflow=arExpected/13+qrev*.92*.35/13;
  const outflow=ap/13+qcost*.74/13;
  base.push(base.at(-1)+inflow-outflow);
  scenario.push(scenario.at(-1)+inflow-outflow+(i<4?recover/4:0)+(savings-inflation)*.74/13);
 }
 return {base,scenario,floor,recover,savings,inflation,overdue,material,arExpected,qcost,ap,grossRecovery,uncollectedOverdue,netProfit:savings-inflation-grossRecovery*.01};
}
function overview(c){
 const overdue=sum(c.ar.filter(x=>x.overdue_days>0),'balance_toman'),risky=c.projects.filter(risk),delta=c.prevRevenue?(c.revenue/c.prevRevenue-1):null;
 const marginal=c.prevMargin!==null?(c.margin-c.prevMargin)*100:null;
 return `<section class="hero"><div><span class="tag">THE EXECUTIVE LENS</span><h2>رشد رصد شود.<br>سرمایه هوشمندانه هدایت شود.</h2><p>${money(overdue)} ${unit()} مطالبات سررسیدگذشته و ${fa(risky.length)} پروژهٔ نیازمند مداخله؛ دو اولویت جلسهٔ هیئت‌مدیره.</p></div><div class="hero-stats"><div class="hero-stat"><strong>${fa(c.projects.length)}</strong><span>پروژه در سبد</span></div><div class="hero-stat"><strong>${fa(new Set(c.projects.map(p=>p.company_id)).size)}</strong><span>شرکت زیرمجموعه</span></div><svg class="building" viewBox="0 0 100 130"><g fill="none" stroke="#d9b572" stroke-width=".8"><path d="M8 110V55l28-15 25 14v58M36 40v70M22 110V18L51 4l32 17v94M51 4v108M67 114V63l24-9v63M8 110l41 16 43-10"/><path d="M26 28l20-10m-20 19 20-10m-20 19 20-10m-20 19 20-10m-20 19 20-10m10-20 22 11m-22 0 22 11m-22 0 22 11m-22 0 22 11m-22 0 22 11m-22 0 22 11"/></g></svg></div></section>
 <div class="kpi-grid">${kpi('درآمد شناسایی‌شده',money(c.revenue),unit(),delta===null?'بدون دورهٔ مقایسه':`${delta>=0?'↑':'↓'} ${percent(Math.abs(delta))} نسبت به سال قبل`,delta===null?'neutral':delta>=0?'positive':'negative')}${kpi('حاشیهٔ سود پروژه‌ها',percent(c.margin),'',marginal===null?'درآمد منهای هزینهٔ پروژه':`${fa(marginal,1)} واحد درصد نسبت به قبل`,marginal===null?'neutral':marginal>=0?'positive':'negative','◒')}${kpi('ماندهٔ نقد برآوردی',money(c.cash),unit(),'ماندهٔ افتتاحیه + خالص جریان','neutral','◈')}${kpi('مطالبات سررسیدگذشته',money(overdue),unit(),percent(overdue/sum(c.ar,'balance_toman'))+' از ماندهٔ مطالبات','warning','◷')}</div>
 <div class="grid-main">${panel('رشد درآمد، مسیر هزینه','روند ماهانه · '+unit(),lineChart(c.periods.map(p=>p.label.split(' ')[0]),[{name:'درآمد',values:sumTrend(c,'revenue_toman'),color:'#833ca3'},{name:'هزینهٔ پروژه',values:sumTrend(c,'cost_toman'),color:'#d79d4b'}]),state.year==='all'?'۳۶ ماه':state.year)}${panel('دستور جلسهٔ مدیرعامل','سه تصمیم، با پشتوانهٔ داده',insight(1,'وصول هدفمند مطالبات',`${money(overdue)} ${unit()} از زمان تعهد پرداخت عبور کرده است. تمرکز بر بزرگ‌ترین مانده‌ها، با بررسی سابقهٔ کارفرما.`,'cash')+insight(2,'بازبینی پروژه‌های پرریسک',`${fa(risky.length)} پروژه بر اساس CPI یا SPI زیر آستانه است؛ بازبینی برآورد هزینهٔ تکمیل در اولویت قرار گیرد.`,'projects')+insight(3,'انضباط خرید و موجودی',`${money(sum(c.all,'stock_delta_toman'))} ${unit()} در موجودی مصالح ثبت شده؛ پیش از خرید جدید، امکان انتقال بین پروژه‌ها بررسی شود.`,'procurement'),'NEXT ACTIONS')}</div>
 ${panel('پروژه‌های اولویت‌دار','شاخص‌های تجمعی تا تاریخ برش · کلیک روی ردیف برای جزئیات',projectsTable(c.projects,5),'PORTFOLIO WATCH')}`;
}
function projectsPage(c){
 const ev=sum(c.projects,'ev_toman'),ac=sum(c.projects,'cost_toman'),pv=sum(c.projects,'pv_toman'),bac=sum(c.projects,'budget_toman'),eac=sum(c.projects,p=>p.progress>=1?p.cost_toman:p.budget_toman/p.cpi);
 return `<div class="kpi-grid">${kpi('ارزش باقی‌ماندهٔ قرارداد',money(sum(c.projects,p=>p.contract_toman-p.revenue_toman)),unit(),'ماندهٔ تعهدات شناسایی‌نشده')}${kpi('کارایی هزینهٔ سبد',fa(ev/ac,2),'CPI','ارزش کسب‌شده ÷ هزینهٔ واقعی',ev/ac>=1?'positive':'warning')}${kpi('کارایی زمان سبد',fa(ev/pv,2),'SPI','ارزش کسب‌شده ÷ ارزش برنامه',ev/pv>=1?'positive':'warning')}${kpi('انحراف برآورد تکمیل',money(eac-bac),unit(),'EAC منهای بودجه؛ تخمین سناریویی',eac>bac?'negative':'positive')}</div>
 <div class="grid-equal">${panel('نقشهٔ ریسک زمان و هزینه','شاخص‌ها از مجموع ارقام محاسبه می‌شوند، نه میانگین درصدها',scatter(c.projects),'AS OF 1404/12/29')}${panel('بودجه و هزینهٔ پیش‌بینی‌شدهٔ تکمیل','برای پروژه‌های باز: EAC = BAC ÷ CPI',bars(c.projects.sort((a,b)=>riskRank(b)-riskRank(a)).slice(0,5).map(p=>({name:p.name,value:Math.max(0,p.budget_toman/p.cpi-p.budget_toman),note:'انحراف برآوردی',color:'#b45e69'})))+'<p class="footnote">EAC فرض می‌کند کارایی هزینهٔ فعلی ادامه یابد. این شاخص جایگزین برآورد مهندسی هزینهٔ تکمیل نیست.</p>')}</div>
 ${panel('دفتر سبد پروژه‌ها','درآمد و هزینه در جزئیات پروژه قابل پیگیری است',`<input class="search" id="project-search" placeholder="جست‌وجوی نام پروژه…" aria-label="جست‌وجوی پروژه"><div id="projects-table">${projectsTable(c.projects)}</div>`,fa(c.projects.length)+' پروژه')}`;
}
function cashPage(c){
 const f=forecast(c),ar=sum(c.ar,'balance_toman'),buckets=[['سررسید نشده',x=>!x.overdue_days],['۱ تا ۳۰ روز',x=>x.overdue_days>0&&x.overdue_days<=30],['۳۱ تا ۹۰ روز',x=>x.overdue_days>30&&x.overdue_days<=90],['۹۱ تا ۱۸۰ روز',x=>x.overdue_days>90&&x.overdue_days<=180],['بیش از ۱۸۰ روز',x=>x.overdue_days>180]];
 const clients={};c.ar.forEach(x=>{const a=clients[x.customer_id]??={id:x.customer_id,balance:0,overdue:0};a.balance+=x.balance_toman;if(x.overdue_days)a.overdue+=x.balance_toman});
 return `<div class="kpi-grid">${kpi('مطالبات باز',money(ar),unit(),'صورتحساب منهای دریافت‌ها')}${kpi('مطالبات سررسیدگذشته',money(f.overdue),unit(),percent(f.overdue/ar)+' از مطالبات','warning')}${kpi('بدهی باز به تأمین‌کنندگان',money(f.ap),unit(),'سفارش خرید منهای پرداخت')}${kpi('ماندهٔ نقد برآوردی',money(c.cash),unit(),'مانده در تاریخ برش')}</div>
 <div class="grid-equal">${panel('سن مطالبات','مبنای سن: تاریخ سررسید؛ تا ۲۹ اسفند ۱۴۰۴',bars(buckets.map(([name,fn],i)=>({name,value:sum(c.ar.filter(fn),'balance_toman'),color:i>2?'#b45e69':'#a17ab0'}))))}${panel('چشم‌انداز نقدینگی ۱۳ هفته‌ای','سناریوی ساده با فرض ادامهٔ نرخ فعالیت سه ماه اخیر',lineChart(['امروز',...Array.from({length:13},(_,i)=>'هفته '+fa(i+1))],[{name:'سناریوی پایه',values:f.base,color:'#833ca3'},{name:'با فرض‌های آزمایشگاه تصمیم',values:f.scenario,color:'#9b6828'}],{minZero:false}))}</div>
 ${panel('اولویت پیگیری وصول','همهٔ مانده‌ها مربوط به تاریخ برش هستند',`<div class="table-wrap"><table><thead><tr><th>کارفرما</th><th>ماندهٔ باز (${unit()})</th><th>سررسیدگذشته (${unit()})</th><th>سهم سررسیدگذشته</th></tr></thead><tbody>${Object.values(clients).sort((a,b)=>b.overdue-a.overdue).slice(0,8).map(x=>`<tr><td>${customerMap[x.id].name}</td><td>${money(x.balance)}</td><td>${money(x.overdue)}</td><td>${pill(percent(x.overdue/x.balance),x.overdue/x.balance>.6?'warning':'neutral')}</td></tr>`).join('')}</tbody></table></div>`)}<div class="callout">پیش‌بینی سناریویی است، نه وعدهٔ وصول: وصول مانده‌ها با ضرایب ۸۸٪، ۷۰٪، ۴۵٪ و ۲۵٪ برحسب سن فرض شده؛ پرداخت ماندهٔ تأمین‌کنندگان طی ۱۳ هفته و پرداخت ۷۴٪ هزینهٔ جدید نیز فرض مدل است. ماندهٔ افتتاحیه برای فیلتر گروه به نسبت قراردادها تخصیص می‌یابد.</div>`;
}
function procurement(c){
 const data=D.supply.filter(x=>c.ids.has(x[0])&&c.periodIds.has(x[1])),vendors={},cats={};
 data.forEach(x=>{const s=supplierMap[x[2]],v=vendors[x[2]]??={id:x[2],name:s.name,amount:0,n:0,late:0,delay:0};v.amount+=x[4];v.n+=x[3];v.late+=x[5];v.delay+=x[6]*x[3];cats[s.category]=(cats[s.category]||0)+x[4]});
 const vs=Object.values(vendors).sort((a,b)=>b.amount-a.amount),total=sum(vs,'amount'),orders=sum(vs,'n'),late=sum(vs,'late');
 return `<div class="kpi-grid">${kpi('سفارش خرید',fa(orders),'سفارش','هر سفارش دارای یک قلم مصالح')}${kpi('ارزش خرید مصالح',money(total),unit(),'خرید با هزینهٔ مصرف متفاوت است')}${kpi('تحویل به‌موقع',percent(orders?(orders-late)/orders:0),'','تحویل تا تاریخ وعده داده‌شده','warning')}${kpi('موجودی مصالح پایان دوره',money(sum(c.all,'stock_delta_toman')),unit(),'مانده در تاریخ برش')}</div>
 <div class="grid-equal">${panel('ترکیب خرید مصالح','سهم از مبلغ خرید در دورهٔ انتخابی',bars(Object.entries(cats).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)))}${panel('تمرکز خرید','بزرگ‌ترین تأمین‌کنندگان از نظر مبلغ',bars(vs.slice(0,5).map(v=>({name:v.name,value:v.amount,note:percent(v.amount/total)+' از کل خرید'})))+`<div class="callout">بزرگ‌ترین تأمین‌کننده ${percent(vs[0]?.amount/total)} از خرید را دارد. تمرکز در سطح گروه مصالح هم ارزیابی شود؛ سهم از کل خرید به‌تنهایی وابستگی فولاد را نشان نمی‌دهد.</div>`)}</div>
 ${panel('کارت عملکرد تأمین‌کنندگان','سهم، تأخیر و مبلغ؛ مبنای گفت‌وگو برای قرارداد خرید',`<div class="table-wrap"><table><thead><tr><th>تأمین‌کننده</th><th>مصالح</th><th>ارزش خرید (${unit()})</th><th>تعداد سفارش</th><th>تحویل به‌موقع</th><th>میانگین تأخیر</th></tr></thead><tbody>${vs.slice(0,8).map(v=>`<tr><td>${v.name}</td><td>${supplierMap[v.id].category}</td><td>${money(v.amount)}</td><td>${fa(v.n)}</td><td>${pill(percent(1-v.late/v.n),v.late/v.n>.45?'negative':'positive')}</td><td>${fa(v.delay/v.n,1)} روز</td></tr>`).join('')}</tbody></table></div>`)}`;
}
function customers(c){
 const leads=sum(c.campaigns,'leads'),wins=sum(c.campaigns,'wins'),open=sum(c.campaigns,'open_leads'),spend=sum(c.campaigns,'spend_toman'),client={};
 c.m.forEach(x=>{const id=projectMap[x.project_id].customer_id;client[id]=(client[id]||0)+x.revenue_toman});
 return `<div class="kpi-grid">${kpi('درآمد قراردادهای B2B',money(c.revenue),unit(),'بر مبنای پیشرفت واقعی پروژه')}${kpi('فرصت فروش شناسایی‌شده',fa(leads),'فرصت','مستقل از قراردادهای جاری')}${kpi('نرخ برد فرصت‌های بسته',percent(wins/Math.max(1,leads-open)),'','برنده ÷ (برنده + ازدست‌رفته)')}${kpi('هزینهٔ توسعهٔ بازار',money(spend),unit(),'جدا از هزینهٔ مستقیم پروژه')}</div>
 <div class="grid-equal">${panel('وضعیت فرصت‌های کسب‌وکار','سه وضعیت مستقل؛ طول میله متناسب با تعداد',bars([{name:'فرصت باز',value:open,note:'فرصت'},{name:'برنده',value:wins,note:'فرصت'},{name:'ازدست‌رفته',value:leads-open-wins,note:'فرصت'}],{count:true})+`<div class="callout">ارزش فرصت‌های باز: ${money(sum(c.campaigns,'pipeline_toman'))} ${unit()}. این مبلغ درآمد قطعی نیست و به قراردادهای فعلی اضافه نشده است.</div>`)}${panel('تمرکز درآمد در کارفرمایان','پنج کارفرمای نخست، در دورهٔ انتخابی',bars(Object.entries(client).map(([id,value])=>({name:customerMap[id].name,value})).sort((a,b)=>b.value-a.value).slice(0,5)))}</div>
 ${panel('عملکرد کانال‌های توسعه بازار','نرخ برد فقط بر فرصت‌های بسته محاسبه می‌شود',`<div class="table-wrap"><table><thead><tr><th>کانال</th><th>فرصت</th><th>برنده</th><th>باز</th><th>نرخ برد</th><th>هزینه (${unit()})</th></tr></thead><tbody>${['مناقصه','ارتباط سازمانی','نمایشگاه'].map(ch=>{const a=c.campaigns.filter(x=>x.channel===ch),n=sum(a,'leads'),o=sum(a,'open_leads'),w=sum(a,'wins');return `<tr><td>${ch}</td><td>${fa(n)}</td><td>${fa(w)}</td><td>${fa(o)}</td><td>${percent(w/(n-o))}</td><td>${money(sum(a,'spend_toman'))}</td></tr>`}).join('')}</tbody></table></div>`)}`;
}
function people(c){
 const pe=D.people.filter(x=>c.ids.has(x.project_id)),pay=D.costs.filter(x=>c.ids.has(x.project_id)&&c.periodIds.has(x.period_id)&&x.category==='payroll'),n=sum(pe,'headcount'),tickets=sum(c.m,'tickets'),breach=sum(c.m,'breached_tickets');
 return `<div class="kpi-grid">${kpi('نیروی انسانی تخصیص‌یافته',fa(n),'نفر','تعداد ثابت در سناریوی داده')}${kpi('هزینهٔ حقوق و دستمزد',money(sum(pay,'amount_toman')),unit(),'قابل تطبیق با ریز حقوق')}${kpi('درخواست‌های ثبت‌شده',fa(tickets),'درخواست','کیفیت، اسناد، تغییر و ایمنی')}${kpi('حل درخواست در SLA',percent(1-breach/tickets),'','حل در حداکثر ۷ روز','warning')}</div>
 <div class="grid-equal">${panel('ترکیب نیروی انسانی','تعداد کارکنان تخصیص‌یافته به پروژه‌ها',bars(['مهندس','تکنسین','کارشناس پروژه','سرپرست','کارگر ماهر'].map(name=>({name,value:sum(pe.filter(x=>x.role===name),'headcount'),note:'نفر'})),{count:true}))}${panel('روند هزینهٔ نیروی انسانی','مبالغ '+unit()+' · بخشی از هزینهٔ مستقیم پروژه',lineChart(c.periods.map(p=>p.label.split(' ')[0]),[{name:'حقوق و دستمزد',color:'#833ca3',values:c.periods.map(p=>sum(pay.filter(x=>x.period_id===p.period_id),'amount_toman'))}]))}</div>
 ${panel('پروژه‌های نیازمند بهبود خدمت','نسبت عبور از SLA، ابزار پایش است و به‌تنهایی علت را اثبات نمی‌کند',`<div class="table-wrap"><table><thead><tr><th>پروژه</th><th>درخواست</th><th>عبور از SLA</th><th>نرخ رعایت SLA</th></tr></thead><tbody>${c.projects.map(p=>{const ms=c.m.filter(x=>x.project_id===p.project_id);return{...p,n:sum(ms,'tickets'),bad:sum(ms,'breached_tickets')}}).sort((a,b)=>b.bad/b.n-a.bad/a.n).slice(0,7).map(p=>`<tr data-project="${p.project_id}"><td>${p.name}</td><td>${fa(p.n)}</td><td>${fa(p.bad)}</td><td>${pill(percent(1-p.bad/p.n),'warning')}</td></tr>`).join('')}</tbody></table></div>`)}`;
}
function decisions(c){
 const f=forecast(c),worst=[...c.projects].sort((a,b)=>riskRank(b)-riskRank(a))[0];
 const controls=`<div class="control"><label>وصول افزوده از مطالبات معوق<strong id="collect-label">${fa(state.collect)}٪</strong></label><input type="range" id="collect" min="0" max="40" value="${state.collect}"><p>وصول طی ۴ هفته؛ با هزینهٔ تشویقی ۱٪. ماندهٔ مطالبات کم می‌شود، درآمد افزایش نمی‌یابد.</p></div><div class="control"><label>کاهش قیمت خرید آتی<strong id="save-label">${fa(state.save)}٪</strong></label><input type="range" id="save" min="0" max="8" step=".5" value="${state.save}"><p>صرفه‌جویی بر خرید فرضی سه ماه آینده، نه هزینه‌های گذشته.</p></div><div class="control"><label>شوک افزودهٔ قیمت مصالح<strong id="inflation-label">${fa(state.inflation)}٪</strong></label><input type="range" id="inflation" min="0" max="25" value="${state.inflation}"><p>تنش در قیمت آینده؛ یک فرض حساسیت‌سنجی و مستقل از نرخ تبدیل نمایشی دلار.</p></div><button class="export-btn" id="reset-scenario">بازگشت به فرض‌های اولیه</button>`;
 return `<div class="strip glass"><strong>فرض → اثر → اقدام</strong><p>سناریوها برای مقایسه‌اند. اعداد خروجی پیش‌بینی قطعی یا نتیجهٔ تجربه‌شده نیستند.</p></div><div class="scenario-grid">${panel('اهرم‌های تصمیم','دامنه‌ها برای آزمایش مدیریتی تعریف شده‌اند',controls)}${panel('اثر بر نقدینگی و هزینه','همهٔ مانده‌ها تا تاریخ برش؛ افق مدل ۱۳ هفته',`<div id="scenario-output">${scenarioOutput(c)}</div>`)}</div>
 <div class="decision-card glass"><div class="rank">01</div><div><h3>برنامهٔ وصول با تمرکز بر مانده‌های بزرگ</h3><p>ابتدا اصالت مطالبات، اختلاف صورت‌وضعیت و توان پرداخت کارفرما بررسی شود. مالک هر پرونده و تاریخ تعهد وصول ثبت شود؛ موفقیت با کاهش ماندهٔ سررسیدگذشته سنجیده شود.</p></div><div class="owner">مالک: مدیر مالی + بازرگانی<br>افق اقدام: ۳۰ روز<br>شاخص: ماندهٔ معوق و وصول</div></div>
 <div class="decision-card glass"><div class="rank">02</div><div><h3>بازبرآورد هزینهٔ تکمیل پروژه‌های پرریسک</h3><p>${worst.name} در اولویت بازبینی است: CPI برابر ${fa(worst.cpi,2)} و SPI برابر ${fa(worst.spi,2)}. گزارش مهندسیِ مسیر بحرانی، تعهدات و کار باقی‌مانده پیش از تزریق بودجه آماده شود.</p></div><div class="owner">مالک: PMO + مدیر پروژه<br>افق اقدام: ۱۴ روز<br>شاخص: EAC و برنامهٔ جبرانی</div></div>
 <div class="decision-card glass"><div class="rank">03</div><div><h3>مذاکرهٔ خرید و انتقال موجودی بین پروژه‌ها</h3><p>مقایسهٔ تأمین‌کنندگان در هر گروه مصالح، بررسی کیفیت و زمان تحویل، سپس مذاکرهٔ آزمایشی. انتقال موجودی فقط پس از تطبیق مشخصات فنی و نیاز مصوب پروژهٔ مقصد انجام شود.</p></div><div class="owner">مالک: خرید + انبار + فنی<br>افق اقدام: ۴۵ روز<br>شاخص: قیمت هم‌سبد و تأخیر</div></div>`;
}
function scenarioOutput(c){const f=forecast(c),delta=f.scenario.at(-1)-f.base.at(-1);return `<div class="scenario-result"><div><small>اثر نقدی ۱۳ هفته · ${unit()}</small><strong style="color:${delta>=0?'var(--teal)':'var(--red)'}">${delta>=0?'+':''}${money(delta)}</strong></div><div><small>اثر بر سود فرضی · ${unit()}</small><strong>${money(f.netProfit)}</strong></div><div><small>کمترین ماندهٔ سناریو · ${unit()}</small><strong>${money(Math.min(...f.scenario))}</strong></div></div>${lineChart(['امروز',...Array.from({length:13},(_,i)=>'هفته '+fa(i+1))],[{name:'پایه',values:f.base,color:'#aa96ad',dashed:true},{name:'سناریوی شما',values:f.scenario,color:'#9b6828'}],{minZero:false,height:245})}<p class="footnote">اثر نقدی = وصول افزوده پس از هزینهٔ تشویقی + ۷۴٪ × (صرفه‌جویی خرید − شوک مصالح). اثر سود شامل اصل مطالبات وصول‌شده نیست. ${money(f.recover)} ${unit()} وصول افزوده فرض شده است.</p>`}
function quality(){const q=D.dq,physical=sum(Object.entries(D.rowCounts).filter(([k])=>!['metadata','dq_audit','dq_quarantine'].includes(k)).map(([k,v])=>({n:v})),'n');return `<div class="lineage"><div class="glass"><span class="stage">01 / SOURCE</span><strong>${fa(q.raw_rows)}</strong><span>ردیف خام سفارش خرید</span></div><div class="glass"><span class="stage">02 / VALIDATE</span><strong>${fa(q.duplicate_order+q.missing_project+q.negative_amount+q.invalid_supplier)}</strong><span>تکراری یا قرنطینه‌شده</span></div><div class="glass"><span class="stage">03 / WAREHOUSE</span><strong>${fa(q.accepted_orders)}</strong><span>سفارش یکتای معتبر</span></div><div class="glass"><span class="stage">04 / DECISION</span><strong>۸ نمای تحلیلی</strong><span>شاخص‌های مشترک و قابل ردیابی</span></div></div>
 <div class="grid-equal">${panel('کیفیت، با مدرک','کنترل‌های ثبت‌شده در qa/data-validation.json',`<div class="quality-number">۱۵ / ۱۵</div><div class="sub">کنترل اصلی داده با موفقیت انجام شده</div><div class="callout">تطبیق هزینهٔ پروژه با ریز هزینه‌ها، حقوق با ریز پرداخت کارکنان، مصرف مصالح با موجودی، دریافتی با رویدادهای نقدی و نبود کلید خارجی نامعتبر.</div><div class="stat-pair"><div><strong>${fa(physical)}</strong><span>رکورد در جداول عملیاتی و تحلیلی</span></div><div><strong>${fa(D.rowCounts.projects)}</strong><span>پروژهٔ ساخت‌وساز</span></div></div>`)}${panel('گزارش پاک‌سازی','هیچ ردیف نامعتبر بدون ثبت دلیل حذف نشده است',`<div class="table-wrap"><table><thead><tr><th>مسئله</th><th>تعداد</th><th>اقدام</th></tr></thead><tbody>${[['سفارش تکراری',q.duplicate_order,'حذف تکرار'],['شناسهٔ پروژهٔ خالی',q.missing_project,'قرنطینه'],['مبلغ منفی نامعتبر',q.negative_amount,'قرنطینه'],['تأمین‌کنندهٔ نامعتبر',q.invalid_supplier,'قرنطینه'],['مبلغ ریالی',q.irr_to_toman,'تبدیل به تومان'],['قالب متفاوت تاریخ',q.date_standardized,'استانداردسازی']].map(x=>`<tr><td>${x[0]}</td><td>${fa(x[1])}</td><td>${pill(x[2])}</td></tr>`).join('')}</tbody></table></div>`)}</div>
 ${panel('تعریف و دامنهٔ شاخص‌ها','شفافیت فرض‌ها، بخشی از نمونه‌کار است',`<div class="table-wrap"><table><thead><tr><th>شاخص</th><th>تعریف</th><th>محدودیت</th></tr></thead><tbody><tr><td>درآمد شناسایی‌شده</td><td>ارزش قرارداد × افزایش پیشرفت واقعی</td><td>مدل مدیریتی ساده؛ قواعد رسمی حسابداری اعمال نشده</td></tr><tr><td>سود پروژه</td><td>درآمد منهای هزینهٔ مستقیم پروژه</td><td>مالیات، هزینهٔ تأمین مالی و سربار مرکزی مدل نشده</td></tr><tr><td>CPI / SPI</td><td>EV ÷ AC / EV ÷ PV</td><td>ارزش کسب‌شده با بودجه سنجیده می‌شود، نه مبلغ فروش</td></tr><tr><td>ماندهٔ نقد</td><td>افتتاحیه + دریافت − پرداخت − بازاریابی</td><td>ماندهٔ شبیه‌سازی‌شده؛ وام و سود سهام مدل نشده</td></tr><tr><td>دلار</td><td>تومان ÷ نرخ فرضی ÷ یک میلیون</td><td>صرفاً تبدیل نمایشی، بدون نرخ زنده</td></tr><tr><td>همت</td><td>هزار میلیارد تومان</td><td>همهٔ محاسبات پایه بر حسب تومان صحیح</td></tr></tbody></table></div>`)}<p class="footnote">داده‌ها از روابط تعریف‌شدهٔ سناریو تولید شده‌اند؛ کشف علت یا اثبات مهارت روی دادهٔ واقعی محسوب نمی‌شوند. کد تولید، SQL، تعاریف شاخص و کنترل‌های کیفیت همراه پروژه‌اند.</p>`}
function render(){
 const metricId=state.page.startsWith('metric/')?state.page.slice(7):null;
 const isMetric=metricId&&metricDetails.title(metricId);
 if(!isMetric&&!pages[state.page])state.page='overview';
 const [title,eyebrow,sub]=isMetric?[metricDetails.title(metricId),'METRIC DETAIL','نمودارها، روش محاسبه و نکتهٔ تفسیر این شاخص.']:pages[state.page];
 $('#title').textContent=title;$('#eyebrow').textContent=eyebrow;$('#subtitle').textContent=sub;
 const activePage=isMetric?(pages[state.returnPage]?state.returnPage:metricDetails.sourcePage(metricId)):state.page;
 document.querySelectorAll('[data-page]').forEach(a=>a.classList.toggle('active',a.dataset.page===activePage));
 const c=context(),handlers={overview,projects:projectsPage,cash:cashPage,procurement,customers,people,decisions,quality};
 $('#content').innerHTML=isMetric?metricDetails.render(metricId,c,{D,sum,money,unit,fa,percent,lineChart,bars,panel,scatter,forecast,projectMap,customerMap,supplierMap,pages,returnPage:state.returnPage}):handlers[state.page](c);
 $('#content').classList.remove('page-enter');void $('#content').offsetWidth;$('#content').classList.add('page-enter');
 $('#scope-note').textContent=state.page==='quality'?'کیفیت داده در کل مجموعه · فیلترها بر این صفحه اعمال نمی‌شوند':`عملکرد: ${state.year==='all'?'تمام ۳۶ ماه':'سال '+fa(state.year)} · مانده‌ها و وضعیت پروژه‌ها: ۲۹ اسفند ۱۴۰۴ · ${unit()}`;
 bindLocal(c);document.title=title+' | هُما';
}
function bindLocal(c){
 $('#project-search')?.addEventListener('input',e=>{$('#projects-table').innerHTML=projectsTable(c.projects.filter(p=>p.name.includes(e.target.value)||p.company_name.includes(e.target.value)))});
 ['collect','save','inflation'].forEach(k=>$('#'+k)?.addEventListener('input',e=>{state[k]=+e.target.value;$('#'+k+'-label').textContent=fa(state[k],k==='save'?1:0)+'٪';$('#scenario-output').innerHTML=scenarioOutput(c)}));
 $('#reset-scenario')?.addEventListener('click',()=>{state.collect=20;state.save=3;state.inflation=5;render()});
}
function detail(id){const p=projectMap[id];if(!p)return;const ms=D.monthly.filter(x=>x.project_id===id&&x.period_id>24),ar=sum(D.receivables.filter(x=>x.project_id===id),'balance_toman');$('#drawer-body').innerHTML=`<div class="eyebrow">PROJECT / ${String(id).padStart(3,'0')}</div><h2>${p.name}</h2><p>${p.company_name} · ${p.location}<br>${p.type} · همهٔ مانده‌ها در تاریخ برش داده</p><div class="kpi-grid">${kpi('ارزش قرارداد',money(p.contract_toman),unit())}${kpi('پیشرفت واقعی',percent(p.progress),'',`برنامه: ${percent(p.planned_progress)}`)}${kpi('کارایی هزینه',fa(p.cpi,2),'CPI',p.cpi<1?'بالاتر از هزینهٔ بودجه‌ای':'در محدودهٔ بودجه',p.cpi<1?'warning':'positive')}${kpi('مطالبات باز',money(ar),unit(),'','neutral','↗',false)}</div>${panel('درآمد و هزینهٔ ۱۲ ماه اخیر',unit(),lineChart(D.periods.slice(24).map(x=>x.label.split(' ')[0]),[{name:'درآمد',values:ms.map(x=>x.revenue_toman),color:'#833ca3'},{name:'هزینه',values:ms.map(x=>x.cost_toman),color:'#d79d4b'}]))}<div class="callout">ارزش کسب‌شده: ${money(p.ev_toman)} ${unit()}<br>هزینهٔ تجمعی: ${money(p.cost_toman)} ${unit()}<br>پیش‌بینی هزینهٔ تکمیل: ${money(p.progress>=1?p.cost_toman:p.budget_toman/p.cpi)} ${unit()}<br>فروض EAC: تداوم کارایی هزینهٔ فعلی.</div>`;$('#backdrop').hidden=false;$('#drawer').hidden=false;$('#close-drawer').focus()}
function closeDetail(){$('#backdrop').hidden=true;$('#drawer').hidden=true}
$('#close-drawer').onclick=closeDetail;$('#backdrop').onclick=closeDetail;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail()});
document.addEventListener('click',e=>{const metric=e.target.closest('[data-metric]');if(metric&&pages[state.page])state.returnPage=state.page;const project=e.target.closest('[data-project]');if(project)detail(+project.dataset.project);const go=e.target.closest('[data-go]');if(go)location.hash=go.dataset.go});
document.addEventListener('pointermove',e=>{const tip=e.target.closest('[data-tip]');if(!tip){$('#tooltip').hidden=true;return}const el=$('#tooltip');el.textContent=tip.dataset.tip;el.hidden=false;el.style.left=Math.max(5,Math.min(e.clientX+12,innerWidth-el.offsetWidth-12))+'px';el.style.top=Math.max(5,e.clientY-el.offsetHeight-15)+'px'});
window.addEventListener('hashchange',()=>{state.page=location.hash.slice(1);render();window.scrollTo(0,0)});
for(const [id,key]of [['period','year'],['group','group'],['unit','unit']])$('#'+id).addEventListener('change',e=>{state[key]=e.target.value;render()});
$('#fx').addEventListener('change',e=>{state.fx=Math.min(1000000,Math.max(1000,Number(e.target.value)||90000));e.target.value=state.fx;render()});
$('#print').onclick=()=>window.print();
$('#export').onclick=()=>{const c=context(),keys=['project_id','period_id','revenue_toman','cost_toman','ev_toman','pv_toman','receipts_toman','payments_toman','orders'];const csv='\ufeff'+keys.join(',')+'\r\n'+c.m.map(x=>keys.map(k=>x[k]).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='homa-filtered-monthly-toman.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('دادهٔ فیلترشده با واحد پایهٔ تومان ذخیره شد.')};
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3000)}
// Deterministic, inspectable hooks for automated QA and the OpenMontage showcase.
window.Homa={state,context,forecast,render,navigate:p=>{state.page=p;render()},setFilters:v=>{Object.assign(state,v);for(const[id,k]of [['period','year'],['group','group'],['unit','unit'],['fx','fx']])$('#'+id).value=state[k];render()},detail,closeDetail};
render();
